name: Publish

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    name: Setup Ubuntu
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - name: Install latest stable
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Install just
        run: sudo apt install just

      - name: Run rust CI
        run: just ci
